name: user
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  shared_preferences: ^2.5.2
  flutter_skeleton_ui: ^0.0.6
  carousel_slider: ^5.0.0
  get: ^4.6.6
  country_code_picker: ^3.2.0
  google_maps_flutter: ^2.10.0
  image_picker: ^1.1.2
  geolocator: ^13.0.2
  url_launcher: ^6.3.1
  share_plus: ^10.1.4
  date_picker_timeline: ^1.2.6
  jiffy: ^6.3.2
  connectivity_plus: ^6.1.3
  webview_flutter: ^4.10.0
  geocoding: ^3.0.0
  google_nav_bar: ^5.0.7
  flutter_widget_from_html: ^0.15.3
  flutter_otp_text_field: ^1.4.0+2
  badges: ^3.1.2
  change_app_package_name: ^1.4.0
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sliders/
    - assets/images/

  fonts:
    - family: bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: semibold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf

    - family: medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
